# --- GERAL ---
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -g allow-rename off

# Cores reais (True Color)
set-option -sa terminal-overrides ",xterm*:Tc"

# --- ATALHOS (Keybindings) ---
set -g prefix C-b
bind C-b send-prefix

# Dividir janelas
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Recarregar configuração
bind r source-file ~/.config/tmux/tmux.conf \; display "Configuração recarregada!"

# Navegar entre painéis com Alt + setas ou Alt + hjkl (sem apertar prefixo)
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Manter o diretório atual
bind c new-window -c "#{pane_current_path}"

# --- ESTILO KONSOLE ---
bind -n S-Left previous-window
bind -n S-Right next-window
bind -n C-t new-window -c "#{pane_current_path}"
bind -n C-S-w kill-window
bind -n C-S-Left swap-window -t -1 \; previous-window
bind -n C-S-Right swap-window -t +1 \; next-window

# --- TEMA VISUAL (HYPRLAND MATCH) ---
set-option -g status-position top
set -g status-style bg='#1a1a1a',fg='#abb2bf'
set -g status-interval 1

# Lado Esquerdo
set -g status-left-length 50
set -g status-left "#[fg='#33ccff',bold]  #S #[fg='#595959']| "

# Lado Direito (Relógio minimalista com a cor laranja)
set -g status-right "#[fg='#ff9933',bold] %H:%M #[fg='#595959']|#[fg='#abb2bf'] %d-%b "

# Janelas (Abas)
set -g window-status-separator "  "
set-window-option -g window-status-format "#[fg='#595959']#I: #[fg='#abb2bf']#W"
set-window-option -g window-status-current-format "#[fg='#33ccff',bold,underline]➜ #I: #W"

# Mensagens e Linha de Comando
set -g message-style bg='#33ccff',fg='#1a1a1a',bold